### ISSUE TITLE
non scroll image

### ISSUE THREAD

**Issue by progsmile** [cocuh/intellij-background-chibichara#6]
Would be very pleased to somebody who can implement fixed image background

**Comment by fyzzy1943** [comment]
yes, and if config can control the size of the picture will be better.

**Comment by progsmile** [comment]
It may work, try:
[background at phpstorm](https://youtrack.jetbrains.com/issue/IDEA-152421)

**Comment by cocuh** [comment]
@progsmile 
Thank you for information! It's what I want!!
I learned how to use it. I want to implement it.

After implementation, this issue will close.

![hoge](https://cloud.githubusercontent.com/assets/1741999/14097612/e03e6302-f5ad-11e5-87a4-bceb301d27f5.png)

**Comment by progsmile** [comment]
)))

**Comment by cocuh** [comment]
i wrote as new plugin. https://github.com/cocuh/intellij-wallpaper

**Comment by fyzzy1943** [comment]
nice :)
