### ISSUE TITLE
Implement .cs file support (JetBrains Rider EAP)

### ISSUE THREAD

**Issue by ghost** [cocuh/intellij-background-chibichara#7]
Hey,

I can't immediately see in the code, but currently this works in JetBrains Rider but not with .cs, .config files for C# etc. Could you look into this? Or help me make my chibi chara appear in Rider properly? :)

ありがとうございました～

**Comment by cocuh** [comment]
It seems to work well in Rider 1.0 EAP. If you can't run correctly, it might be different problem, e.g. forgetting to add chibichara image files in configuration menu or setting transparent parameter `alpha` to 0.

![hoge](https://cloud.githubusercontent.com/assets/1741999/21668135/50f532d4-d342-11e6-8722-0aa94c0db7b1.png)
